### ISSUE TITLE
Resources not embedded when building on Teamcity

### ISSUE THREAD

**Issue by danbris** [MarcStan/resource-embedder#22]
Hello,

Not sure if this is maintained anymore, but I have a strange situation. 

First of all, this might not be a Resource.Embedder issue but probably something that can influence its behavior.

On my system the build works ok, but on Teamcity resources are not embedded. It used to work on Teamcity also, but with a new project it doesn't work anymore. I think it must be related to some parameters or configuration, but I was wondering if maybe this happened to somebody else or if someone has knowledge of what could block the embedder from running. The package is there, restored each time.

This is the build step configuration in TeamCity:
![image](https://user-images.githubusercontent.com/32664315/111279994-fa960a80-8643-11eb-9244-b1f8e5eafec1.png)

**Details:**

  - .Net Version: 4.6.1
  - Platform/OS Version: Windows 10
  - Additional details: MSBuild version = 16.6.0 on Teamcity and 16.8.3 on local PC.

Any info/hint/detail is highly appreciated.

Thanks,
Dani

**Comment by MarcStan** [comment]
Hey, do you by any chance have any logs from teamcity?
The exact msbuild command (incl. arguments) would be helpful as well.

The embedder should log some warnings/infos such as `Looking for references in: <folders>`/ `Finished embedding cultures: ...` that could give some hints.

**Comment by danbris** [comment]
Hi Marc, 
This is the detailed build log from TeamCity. Hope it helps.

[build log.txt](https://github.com/MarcStan/resource-embedder/files/6154110/build.log.txt)

**Comment by MarcStan** [comment]
The one difference I found between your screenshot and the log is that in the log the project `ProjectB.Installer\ProjectB.Installer.csproj` as opposed to ``Project.Installer` is being built.
Not sure if the difference is on purpose..

Other than that I had a look and even though `Resource.Embedder 2.1.1` nuget is restored it doesn't seem to run at all even though there are clearly some resource files which is strange.

I can't find the `EmbedderTarget` task in your log which should have been hooked into MSBuild.
It should run directly after .Net's own `GenerateSatelliteAssemblies` task and look something like this:

```
EmbedderTarget:
  Looking for references in: <list of directories>
  Rewriting debug symbols with PdbWriterProvider
  Finished embedding cultures: de into exe in 319ms
```

Can you maybe try to completely remove the embedder from your project (also make sure to remove any references inside your csproj) and re-add it?

Other than that try to maybe setting up a new TeamCity build? If it's a config issue a new one might work?

**Comment by danbris** [comment]
> The one difference I found between your screenshot and the log is that in the log the project ProjectB.Installer\ProjectB.Installer.csproj as opposed to ``Project.Installer` is being built.

This was just some typo in the teamcity config, but nothing important.
I will try to remove embedder from project and do a new build and the re-add it and see if something changes.
Do you have any idea what could prevent Embedder to run at all? Access rights or maybe the files that should be embedded are not present or the files are locked by another process... things like this?

**Comment by MarcStan** [comment]
There was indeed a case where someone had the project inside dropbox and the background sync caused issues (see #8) but the build caused errors due to file locks instead of just silently doing nothing (also I don't think you have dropbox or similar sync setup on your TeamCity server..).

In the log I can see one non-default resource file (de-DE) that should be embedded into the executable/dll but it's not happening.
The embedder workflow should be triggered by MSBuild automatically based on [msbuild targets](https://github.com/MarcStan/resource-embedder/blob/master/src/ResourceEmbedder.MsBuild/build/Resource.Embedder.props). (In your case the `GenerateSatelliteAssemblies` target is running so it should invoke the embedder automatically and I don't understand myself why that's not happening).

You mentioned that it used to work on TeamCity so I'm inclined to say it must be something on your server that changed?

**Comment by MarcStan** [comment]
I'll close this for now because it doesn't seem to be a bug of the library.

Fell free to reopen if you find any indication otherwise.
